language: r
#cache: packages
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository ppa:opencpu/jq --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev
  - sudo apt-get install --yes libjq-dev libprotobuf-dev libprotoc-dev protobuf-compiler

r_packages:
  - rgdal
  - sf
  - devtools

script:
  - R CMD INSTALL ../geocompr/
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
