language: r
cache: packages
latex: false
dist: bionic
sudo: required
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
     - ccache
     - libprotobuf-dev
     - protobuf-compiler
     - libv8-dev
     - libjq-dev
     - libudunits2-dev
     - libproj-dev
     - libgeos-dev
     - libgdal-dev
     - libnetcdf-dev
     - netcdf-bin
     - r-cran-tidyvers
     - r-cran-readr
     - r-cran-stringi
     - r-cran-data.table
     - r-cran-bh
     - r-cran-rgdal

install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('tinytex')"
  - R -e "tinytex::install_tinytex()"
  - R -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat/', type = 'source')"
  - R -e "remotes::install_github('geocompr/geocompkg')"


script:
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
  - MAKEFLAGS="-j 2"
