on:
  push:
    branches:
      main
  
name: Render

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    services:
      postgres:
        image: kartoza/postgis
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgis
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology
          DEFAULT_ENCODING: "UTF8"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          crayon.enabled: 'FALSE' 

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install pak and query dependencies
        run: |
          install.packages("remotes")
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::local_dev_deps_tree(), ".github/r-depends.rds")
        shell: Rscript {0}
        
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}
            !${{ env.R_LIBS_USER }}/pak
          key: ${{ runner.os }}-${{ steps.get-r-version.outputs.version }}-4-

      - name: Install system dependencies
        run: |
          #Rscript -e "remotes::install_github('r-hub/sysreqs')"
          #sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          #sudo -s eval "$sysreqs"
          # install spatial dependencies
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt install \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libv8-dev \
            libjq-dev \
            libprotobuf-dev \
            protobuf-compiler
          # install database dependencies
          sudo apt-get -y install bash-completion wget
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get -y install postgresql-client-12

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
          remotes::install_github("geocompr/geocompkg", dependencies = TRUE)
          remotes::install_github("rspatial/terra") #temporary, remove later
        shell: Rscript {0}

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages  
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
